### ISSUE TITLE
Xray以后版本为什么国内网站无法访问

### ISSUE THREAD

**Issue by tokyoliyi** [SuLingGG/OpenWrt-Docker#15]
树莓派3B的机器，刷了2021-01-03-OPENFANS-Debian-Buster-Aarch64-ext4-v2021-2.0-U6-Release-plus++.img.xz镜像
试了rpi2、rpi3的版本，passwall国外正常国内不行。即便是不开启passwall，国内也不正常。ping www.baidu.com时候，DNS勉强能出来，但是后面超时了。容器内Ping www.baidu.com是正常的，难道是防火墙规则的问题？

**Comment by tokyoliyi** [comment]
找到问题了，接口 - LAN网络里面，物理设置，取消桥接接口，应用即可。

**Comment by 0x1af2aec8f957** [comment]
@tokyoliyi good job

**Comment by tokyoliyi** [comment]
> @tokyoliyi 这个方法及时解决了我的问题，非常感谢。
不客气，互相帮助。

**Comment by huangqingchao** [comment]
@tokyoliyi 我不开passwall的时候也是上不了网，开了passwall之后全局就不能上，然后根据你的取消桥接解决了。但是取消桥接后，不开passwall可以联网，开了passwall就感觉dns挂了，域名解析不到，国内外都可以，ping ip可以通...

**Comment by lyq1996** [comment]
> @tokyoliyi 我不开passwall的时候也是上不了网，开了passwall之后全局就不能上，然后根据你的取消桥接解决了。但是取消桥接后，不开passwall可以联网，开了passwall就感觉dns挂了，域名解析不到，国内外都可以，ping ip可以通...

我也是，然后用smart dns了
