### ISSUE TITLE
旁路由模式，OP自己可以上网，其他链接的机器不能上网

### ISSUE THREAD

**Issue by luoyueliang** [SuLingGG/OpenWrt-Docker#17]
OpenWrt R21.1.18 / LuCI Master (git-20.343.54716-6fc079f)

自己可以上网，SSR+跑起来后，也能翻墙，

但就是其他机器不能上网

**Comment by huangqingchao** [comment]
一样的问题，试了好多次，找不到原因

**Comment by rapidacc** [comment]
https://github.com/SuLingGG/OpenWrt-Rpi-Docker/issues/13#issuecomment-748563174

**Comment by 52js** [comment]
大佬，解决了没？我也是这样，只有自己能上网，连接的设备都没网络，换了好几个op都不行，应该是哪里没设置对
