### ISSUE TITLE
X86-64 PC上Ubuntu中docker安装，openwrt中smb共享文件只有百兆级别的10MB传输速度。

### ISSUE THREAD

**Issue by whwtf** [SuLingGG/OpenWrt-Docker#22]
X86-64 PC上Ubuntu中docker安装，openwrt中smb共享文件只有百兆级别的10MB传输速度。怎样能改善呢？主路由及网线都是千兆的。

**Comment by SuLingGG** [comment]
制约条件太多，基本无法排查。
另外你的宿主机已经是 Ubuntu 了，建议直接用 Ubuntu 搭建 SMB 服务。
如果你确实有共享 OpenWrt 容器内文件的需求，可以用 Docker 的 -v 命令把相关文件目录挂载到宿主机，然后用宿主机 (Ubuntu) 的 SMB 服务。
详情百度。

**Comment by whwtf** [comment]
> 制约条件太多，基本无法排查。
> 另外你的宿主机已经是 Ubuntu 了，建议直接用 Ubuntu 搭建 SMB 服务。
> 如果你确实有共享 OpenWrt 容器内文件的需求，可以用 Docker 的 -v 命令把相关文件目录挂载到宿主机，然后用宿主机 (Ubuntu) 的 SMB 服务。
> 详情百度。

也对，直接用Ubuntu到有180MB左右。

**Comment by kingzleshe** [comment]
我之前树莓派装的ubuntu20.04 也遇到同样的问题，
后来改用树莓派直接刷openwrt了
