### ISSUE TITLE
可以添加PassWall+吗

### ISSUE THREAD

**Issue by jiajiaxd** [SuLingGG/OpenWrt-Docker#23]
PassWall+支持ChinaDNS啥的，还是很好用的
但是这个固件里没有加

**Comment by Nlqqer** [comment]
passwall+是什么？能给个链接么

**Comment by Nlqqer** [comment]
> PassWall+支持ChinaDNS啥的，还是很好用的
> 但是这个固件里没有加

passwall+是什么，能给个链接之类的吗

**Comment by jiajiaxd** [comment]
https://github.com/kenzok8/small
