### ISSUE TITLE
宿主机无法上网

### ISSUE THREAD

**Issue by Zeeshan975** [SuLingGG/OpenWrt-Docker#27]
主路由：RM2100已刷pandavan
宿主机：树莓派4b 爱好者基地带桌面版
1、在/etc/network/interfaces添加教程内容，重启后，树莓派无法上网。
pre-up ip link add macvlan link eth0 type macvlan mode bridge
post-down ip link del macvlan link eth0 type macvlan mode bridge
2、在网络-接口-LAN-关闭物理桥接后，局域网其他设备才能上网，树莓派仍无法上网。可能是上面两条应该改一下？但我不懂怎么改。（我删掉这两条后树莓派依旧无法上网）
3、我唯一能想到的解决办法就是主路由刷openwrt了

**Comment by Blake2Wang** [comment]
搜了一圈不知道如何解决？我的情况是树莓派能上网，但是容器内部好像dns有问题，直接用ip能通，域名不能通
