### ISSUE TITLE
希望docker启动命令可以映射宿主机的配置文件目录

### ISSUE THREAD

**Issue by fraee** [SuLingGG/OpenWrt-Docker#28]
`docker run --restart always --name openwrt -d --network macnet --privileged registry.cn-shanghai.aliyuncs.com/suling/openwrt:latest /sbin/init`

这是原启动命令  希望可以添加-V命令  把openwrt和需要在容器内修改的配置文件全部映射出来  以后就可以放心使用docker pull更新镜像了  不然手动更新配置文件很繁琐

只是建议  希望采纳   谢谢

祝好！

**Comment by OnceAce** [comment]
映射可以有，但是问题来了，插件的配置文件存放在哪这个真不知道，那个smartdns配置那么多dns地址，更新OP说没就说

**Comment by orangejx** [comment]
> 映射可以有，但是问题来了，插件的配置文件存放在哪这个真不知道，那个smartdns配置那么多dns地址，更新OP说没就说

没错了, 我也很疑惑这个问题, 原版的`openwrtorg/rootfs`我也不太明白怎么持久化配置文件. 而且有的`-v`持久化并不能正常工作
