### ISSUE TITLE
分享一个关于MACVLAN的方案

### ISSUE THREAD

**Issue by kingzleshe** [SuLingGG/OpenWrt-Docker#31]
VPN 通过公网地址做级联
树莓派 mydomain:5555
OP软路由 mydomain:6666

![image](https://user-images.githubusercontent.com/20214409/126023233-170ac08b-c9c7-496b-ae9a-1346e98341de.png)

**Comment by fflrichard** [comment]
为啥这么复杂？

**Comment by kingzleshe** [comment]
1.简化OP侧VPN配置和其他的配置，大多配置在宿主机上，OP容器目前没良好的升级和备份机制
2.如果你局域网内有不要密码就能访问的共享文件夹，实现了OP上网与局域网资源之间的隔离，有时候只是想给其他手机或者其他人临时用下OP上网。
3.配置阶段比较复制，最终自己使用的时候我感觉还算方便。同1个域名连接vpn实现不同的访问需求。

4.其实单独买个设备做软路由和宿主机分开也就没这个问题，目前属于爱折腾吧。
