### ISSUE TITLE
配置文件应该如何保存呢? docker 一重启数据就都没了啊

### ISSUE THREAD

**Issue by orangejx** [SuLingGG/OpenWrt-Docker#32]
我一直有个疑问❓ 
docker 版的 openwrt 应该如何保存数据/配置呢? 
容器一重启数据就都没了啊. 
原版的`openwrtorg/rootfs`我也一直没想明白

**Comment by kingzleshe** [comment]
你宿主机系统问题吧。我用起重启没问题

**Comment by orangejx** [comment]
> 你宿主机系统问题吧。我用起重启没问题

除了持久化的数据, 所有其他数据都会被恢复...

**Comment by SuLingGG** [comment]
> > 你宿主机系统问题吧。我用起重启没问题
> 
> 除了持久化的数据，所有其他数据都会被恢复...

这是老黄历下的 Docker 了。稍微新一点的 Docker 版本早就不存在这个问题了。
