### ISSUE TITLE
我用这个之后，我的网络带宽只剩下5M了。。。

### ISSUE THREAD

**Issue by 1269146988** [SuLingGG/OpenWrt-Docker#34]
用docker启动的。弄完发现网速特别慢。只是启动了openwrt，没开ssr，带宽只剩5M，然后我又换了一个别人的镜像，发现带宽可以跑满。

**Comment by 1269146988** [comment]
我用的是X86_64的镜像。而且你这个我还必须去取消一下桥接才可以上网。觉得很奇怪

**Comment by SuLingGG** [comment]
唉...你觉得奇怪我也无能为力...

**Comment by SuLingGG** [comment]
唉...你觉得奇怪我也无能为力...
