### ISSUE TITLE
failed to create the macvlan port: operation not supported.

### ISSUE THREAD

**Issue by Alfxjx** [SuLingGG/OpenWrt-Docker#63]
树莓派4b on ubuntu server 2004
docker start openwrt

`docker: Error response from daemon: failed to create the macvlan port: operation not supported.`

`modprobe pppoe` 未找到模块，是和这个有关吗，是不是我选择的系统内核有问题

```
root@ubuntu:/lib# cat /proc/version_signature
Ubuntu 5.15.0-1005.5-raspi 5.15.30
```

使用的是armv8镜像

**Comment by Alfxjx** [comment]
使用的是armv8 镜像

**Comment by Alfxjx** [comment]
可能是和系统有关系 换了树莓派系统现在可以了

**Comment by MRDOCTOROO** [comment]
同样遇到这个问题了，用的4b装的ubuntu sever 无论是使用树莓派4b的镜像还是armv8的都会报这个

**Comment by xiaokexiang** [comment]
> 同样遇到这个问题了，用的4b装的ubuntu sever 无论是使用树莓派4b的镜像还是armv8的都会报这个

`ubuntu22.04lts`，执行`apt install linux-modules-extra-raspi`后重启，就可以正常安装了
